2024-12-05 19:31:11,129 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 19:31:19,945 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 19:35:14,787 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 19:35:47,511 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 19:40:43,161 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 19:41:36,547 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 19:42:38,573 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 19:48:54,994 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 19:50:53,760 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 19:51:10,024 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 19:53:52,016 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 19:55:41,195 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 19:58:42,283 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 19:59:20,937 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 20:06:37,474 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 20:07:32,825 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 20:11:19,008 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 20:12:27,292 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 20:13:22,255 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 20:14:01,956 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 20:15:34,829 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 20:15:37,558 ERROR: Exception on / [GET] [in /home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/app/routes.py", line 25, in index
    return render_template('index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/lucas/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/lucas/microblog/app/templates/base.html", line 107, in top-level template code
    {% include 'navbar.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/lucas/microblog/app/templates/navbar.html", line 38, in template
    <a class="nav-link" href="{{ url_for('logout') }}">Logout</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endif'. The innermost block that needs to be closed is 'if'.
2024-12-05 20:15:37,747 ERROR: Exception on /favicon.ico [GET] [in /home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/app/routes.py", line 168, in church_detail
    church = Church.query.filter_by(church_name=formatted_name).first_or_404()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask_sqlalchemy/query.py", line 46, in first_or_404
    abort(404, description=description)
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/helpers.py", line 277, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/werkzeug/exceptions.py", line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1341, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1281, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/app/errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/lucas/microblog/app/templates/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/lucas/microblog/app/templates/base.html", line 107, in top-level template code
    {% include 'navbar.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/lucas/microblog/app/templates/navbar.html", line 38, in template
    <a class="nav-link" href="{{ url_for('logout') }}">Logout</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endif'. The innermost block that needs to be closed is 'if'.
2024-12-05 20:16:24,489 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 20:17:14,984 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 20:21:23,629 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-05 20:26:34,435 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
